[package]
name = "microservice-comparison-rust"
version = "0.0.0"
authors = ["Stephen Solka <stephen0q@gmail.com>"]

[dependencies]
reqwest = "0.8.8"
json = "0.11.3"
actix-web = "0.7.3"
futures = "0.1.23"